# Generated by Django 5.2.6 on 2025-09-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='article_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='article_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='article_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
